"""Create table RouteStop

Revision ID: 6a20b8fdc1c7
Revises: 7a781d5d2356
Create Date: 2022-06-21 23:17:30.343682

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a20b8fdc1c7'
down_revision = '7a781d5d2356'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_stop',
    sa.Column('route_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('stop_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'stop_id', 'distance')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_stop')
    # ### end Alembic commands ###
